name: Bazel Release

on:
  release:
    types: [published]

jobs:
  # Release archives are not stable on GitHub. A stable release archive is
  # recommended for bzlmod consumers.
  # See: https://blog.bazel.build/2023/02/15/github-archive-checksum.html
  release-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: git archive $GITHUB_REF -o "doctest-${GITHUB_REF:10}.tar.gz"
      - run: gh release upload ${GITHUB_REF:10} "doctest-${GITHUB_REF:10}.tar.gz"
        env:
          GH_TOKEN: ${{ github.token }}
